import { auth, db } from './lib/firebase.js';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';

const STYLE_ID='mx-enterprise-admin-style';
const SHELL_ID='mxEnterpriseAdmin';
const profile=()=>window.__MAURIONE_ADMIN_CONTEXT__||{};
const state={cars:[],stats:[],admins:[],activity:[],view:'dashboard',search:'',mobileMenu:false,stops:[]};
let started=false;
let renderQueued=false;

const icons={
 dashboard:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>',
 cars:'<svg viewBox="0 0 24 24"><path d="M5 17h14l1-5-2-5H6l-2 5 1 5Z"/><circle cx="7" cy="17" r="2"/><circle cx="17" cy="17" r="2"/><path d="M6 7 8 3h8l2 4"/></svg>',
 analytics:'<svg viewBox="0 0 24 24"><path d="M4 20V10"/><path d="M10 20V4"/><path d="M16 20v-7"/><path d="M22 20V8"/></svg>',
 team:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="8.5" cy="7" r="4"/><path d="M20 8v6"/><path d="M23 11h-6"/></svg>',
 users:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
 activity:'<svg viewBox="0 0 24 24"><path d="M3 12h4l3-8 4 16 3-8h4"/></svg>',
 settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 0 0-1.88-.34A1.7 1.7 0 0 0 14.7 20v.1h-5v-.1a1.7 1.7 0 0 0-1.04-1.55 1.7 1.7 0 0 0-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 5 15a1.7 1.7 0 0 0-1.55-1.04h-.1v-3h.1A1.7 1.7 0 0 0 5 9.92a1.7 1.7 0 0 0-.34-1.88L4.6 7.98l2.12-2.12.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 9.7 4.7v-.1h5v.1a1.7 1.7 0 0 0 1.04 1.55 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.12 2.12-.06.06a1.7 1.7 0 0 0-.34 1.88 1.7 1.7 0 0 0 1.55 1.04h.1v3h-.1A1.7 1.7 0 0 0 19.4 15Z"/></svg>',
 plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
 external:'<svg viewBox="0 0 24 24"><path d="M14 3h7v7"/><path d="m10 14 11-11"/><path d="M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"/></svg>',
 search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>',
 menu:'<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',
 close:'<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>',
 bell:'<svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg>',
 chevron:'<svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>',
 eye:'<svg viewBox="0 0 24 24"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>',
 wa:'<svg viewBox="0 0 24 24"><path d="M20.5 11.5a8.5 8.5 0 0 1-12.7 7.4L3 20l1.2-4.6A8.5 8.5 0 1 1 20.5 11.5Z"/><path d="M8.5 8.5c.6 2.8 2.2 4.4 5 5"/></svg>',
 phone:'<svg viewBox="0 0 24 24"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.4 19.4 0 0 1-6-6 19.8 19.8 0 0 1-3.1-8.7A2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1.9.3 1.8.6 2.6a2 2 0 0 1-.5 2.1L8 9.7a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.8.3 1.7.5 2.6.6a2 2 0 0 1 2 2.3Z"/></svg>',
 heart:'<svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/></svg>'
};

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v){return new Intl.NumberFormat('en-US').format(Number(v||0))}
function money(v){return Number(v)>0?`${num(v)} MRU`:'السعر عند التواصل'}
function dateText(value){try{const d=value?.toDate?.()||new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('ar-MR',{year:'numeric',month:'short',day:'numeric'}).format(d)}catch{return '—'}}
function can(permission){const p=profile();return Boolean(p.isOwner||p.permissions?.[permission])}
function carTitle(c){return `${c.brand||''} ${c.model||''} ${c.year||''}`.trim()}
function statTotals(){
 const total={views:0,whatsappClicks:0,phoneClicks:0,favoriteAdds:0};
 state.stats.forEach(s=>{if(String(s.id).startsWith('visitor-count-'))return;for(const k of Object.keys(total))total[k]+=Number(s[k]||0)});
 return total;
}
function visitorDays(){
 const rows=state.stats.filter(s=>/^visitor-count-day-\d{4}-\d{2}-\d{2}$/.test(s.id)).map(s=>({day:s.id.slice(-10),value:Number(s.views||0)})).sort((a,b)=>a.day.localeCompare(b.day));
 return rows.slice(-7);
}
function visitorTotal(){return Number(state.stats.find(s=>s.id==='visitor-count-total')?.views||0)}

function ensureStyle(){
 if(document.getElementById(STYLE_ID))return;
 const style=document.createElement('style');style.id=STYLE_ID;style.textContent=`
 :root{--ent-bg:#f4f6f8;--ent-card:#fff;--ent-text:#111827;--ent-muted:#7b8493;--ent-line:#e6e9ee;--ent-soft:#f8f9fb;--ent-sidebar:#111318;--ent-sidebar2:#181b21;--ent-orange:#f5672b;--ent-green:#168b55;--ent-red:#c44a42;--ent-shadow:0 8px 30px rgba(16,24,40,.06)}
 html[data-theme='dark']{--ent-bg:#0c0f13;--ent-card:#15191e;--ent-text:#f3f5f7;--ent-muted:#9299a4;--ent-line:#2b3139;--ent-soft:#11151a;--ent-sidebar:#090b0e;--ent-sidebar2:#12161b;--ent-shadow:0 8px 30px rgba(0,0,0,.24)}
 body.mxEnterpriseActive{background:var(--ent-bg)!important;overflow-x:hidden!important}
 body.mxEnterpriseActive .mxAdmin>.mxAdminHeader,body.mxEnterpriseActive .mxAdmin>.mxAdminInner{position:absolute!important;left:-10000px!important;top:0!important;width:2px!important;height:2px!important;overflow:hidden!important;opacity:0!important;pointer-events:none!important}
 body.mxEnterpriseActive .mxAdmin>.mxModal{position:fixed!important;inset:0!important;z-index:25000!important;opacity:1!important;pointer-events:auto!important}
 #${SHELL_ID}{min-height:100vh;background:var(--ent-bg);color:var(--ent-text);font-family:Arial,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;direction:rtl;display:grid;grid-template-columns:minmax(0,1fr) 272px}
 #${SHELL_ID} *{box-sizing:border-box}
 #${SHELL_ID} svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
 .entSidebar{grid-column:2;position:sticky;top:0;height:100vh;background:linear-gradient(180deg,var(--ent-sidebar),var(--ent-sidebar2));color:#fff;padding:24px 16px 18px;display:flex;flex-direction:column;z-index:100}
 .entBrand{direction:ltr;font-size:28px;font-weight:950;letter-spacing:-1.5px;padding:5px 10px 22px;text-align:left}.entBrand b{color:#fff}.entBrand i{color:var(--ent-orange);font-style:normal}
 .entCompany{padding:0 10px 18px;border-bottom:1px solid rgba(255,255,255,.09);margin-bottom:15px}.entCompany strong{display:block;font-size:12px}.entCompany small{display:block;color:#89919d;font-size:9px;margin-top:4px;letter-spacing:.4px}
 .entNav{display:grid;gap:5px}.entNav button{height:48px;border:0;background:transparent;color:#9da4af;border-radius:13px;padding:0 13px;display:flex;align-items:center;gap:11px;font-size:13px;font-weight:800;cursor:pointer;text-align:right}.entNav button:hover{background:rgba(255,255,255,.05);color:#fff}.entNav button.active{background:rgba(245,103,43,.13);color:#ff834e}.entNav button.active svg{stroke:#ff834e}
 .entNavLabel{padding:17px 12px 7px;color:#5f6772;font-size:8px;font-weight:900;letter-spacing:1.2px}
 .entSidebarBottom{margin-top:auto;border-top:1px solid rgba(255,255,255,.08);padding-top:13px}.entProfile{display:grid;grid-template-columns:38px minmax(0,1fr);gap:9px;align-items:center;padding:9px;border-radius:13px;background:rgba(255,255,255,.04)}.entAvatar{width:38px;height:38px;border-radius:12px;background:#292e36;display:grid;place-items:center;font-weight:900;color:#ff834e}.entProfile strong{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.entProfile small{display:block;color:#78808c;font-size:8px;margin-top:3px}
 .entMain{grid-column:1;min-width:0}.entTopbar{height:82px;position:sticky;top:0;z-index:80;background:color-mix(in srgb,var(--ent-card) 90%,transparent);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border-bottom:1px solid var(--ent-line);display:flex;align-items:center;justify-content:space-between;padding:0 30px;gap:18px}.entTopTitle{min-width:0}.entTopTitle h1{font-size:20px;margin:0;font-weight:950}.entTopTitle p{font-size:9px;color:var(--ent-muted);margin:5px 0 0}.entTopActions{display:flex;align-items:center;gap:9px}.entIconButton,.entPrimary,.entSecondary{border-radius:12px;border:1px solid var(--ent-line);height:42px;background:var(--ent-card);color:var(--ent-text);display:flex;align-items:center;justify-content:center;gap:7px;padding:0 13px;font-weight:850;cursor:pointer}.entIconButton{width:42px;padding:0}.entPrimary{background:var(--ent-orange);border-color:var(--ent-orange);color:#fff}.entSecondary{background:var(--ent-card)}.entMobileMenu{display:none}
 .entContent{width:min(calc(100% - 48px),1320px);margin:0 auto;padding:26px 0 54px}.entHero{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:18px}.entHero h2{font-size:27px;line-height:1.2;margin:0;font-weight:950;letter-spacing:-.6px}.entHero p{color:var(--ent-muted);font-size:11px;margin:7px 0 0}.entHeroActions{display:flex;gap:8px;flex-wrap:wrap}
 .entKpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:14px}.entKpi{position:relative;overflow:hidden;min-height:132px;border:1px solid var(--ent-line);border-radius:19px;background:var(--ent-card);padding:18px;box-shadow:var(--ent-shadow)}.entKpiTop{display:flex;align-items:center;justify-content:space-between;gap:10px}.entKpiIcon{width:40px;height:40px;border-radius:12px;display:grid;place-items:center;background:var(--ent-soft);color:var(--ent-muted)}.entKpiIcon.orange{background:#fff0e8;color:var(--ent-orange)}.entKpiIcon.green{background:#eaf8f1;color:var(--ent-green)}.entKpiIcon.red{background:#fff0ef;color:var(--ent-red)}html[data-theme='dark'] .entKpiIcon.orange{background:#2c1b14}html[data-theme='dark'] .entKpiIcon.green{background:#10271d}html[data-theme='dark'] .entKpiIcon.red{background:#2a1818}.entKpiLabel{font-size:10px;color:var(--ent-muted);font-weight:800}.entKpi strong{display:block;font-size:30px;margin-top:15px;line-height:1;font-weight:950;direction:ltr;text-align:right}.entKpi small{display:block;color:var(--ent-muted);font-size:8.5px;margin-top:8px}
 .entGrid2{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.75fr);gap:14px}.entCard{border:1px solid var(--ent-line);border-radius:20px;background:var(--ent-card);box-shadow:var(--ent-shadow);overflow:hidden}.entCardHead{min-height:62px;padding:15px 18px;border-bottom:1px solid var(--ent-line);display:flex;align-items:center;justify-content:space-between;gap:12px}.entCardHead h3{margin:0;font-size:15px;font-weight:950}.entCardHead span{font-size:9px;color:var(--ent-muted)}.entCardBody{padding:16px 18px}.entLinkButton{border:0;background:transparent;color:var(--ent-orange);font-size:10px;font-weight:900;cursor:pointer}
 .entTableWrap{overflow:auto}.entTable{width:100%;border-collapse:collapse;min-width:760px}.entTable th{height:44px;padding:0 12px;text-align:right;color:var(--ent-muted);font-size:8.5px;font-weight:900;border-bottom:1px solid var(--ent-line);background:var(--ent-soft)}.entTable td{padding:10px 12px;border-bottom:1px solid var(--ent-line);font-size:10px;vertical-align:middle}.entTable tr:last-child td{border-bottom:0}.entCarCell{display:grid;grid-template-columns:50px minmax(0,1fr);gap:10px;align-items:center}.entCarThumb{width:50px;height:42px;border-radius:10px;object-fit:cover;background:var(--ent-soft)}.entCarCell strong{display:block;font-size:11px}.entCarCell small{display:block;color:var(--ent-muted);font-size:8px;margin-top:3px}.entBadge{display:inline-flex;align-items:center;justify-content:center;height:25px;padding:0 9px;border-radius:999px;font-size:8px;font-weight:900;background:var(--ent-soft);color:var(--ent-muted)}.entBadge.available{background:#eaf8f1;color:var(--ent-green)}.entBadge.sold{background:#fff0ef;color:var(--ent-red)}html[data-theme='dark'] .entBadge.available{background:#10271d}html[data-theme='dark'] .entBadge.sold{background:#2a1818}.entRowActions{display:flex;gap:5px}.entMini{height:30px;border:1px solid var(--ent-line);border-radius:9px;background:var(--ent-card);color:var(--ent-text);padding:0 9px;font-size:8px;font-weight:850;cursor:pointer}.entMini.danger{color:var(--ent-red)}
 .entBars{height:220px;display:flex;align-items:flex-end;gap:10px;padding:20px 4px 3px}.entBarCol{flex:1;min-width:0;text-align:center}.entBarTrack{height:164px;display:flex;align-items:flex-end;justify-content:center}.entBar{width:min(34px,70%);min-height:4px;border-radius:8px 8px 4px 4px;background:linear-gradient(180deg,#ff8a54,var(--ent-orange))}.entBarCol strong{display:block;font-size:9px;margin-top:7px}.entBarCol span{display:block;color:var(--ent-muted);font-size:7px;margin-top:3px}
 .entEngagement{display:grid;gap:8px}.entEngRow{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:10px;align-items:center;padding:9px;border:1px solid var(--ent-line);border-radius:13px;background:var(--ent-soft)}.entEngIcon{width:38px;height:38px;border-radius:11px;background:var(--ent-card);display:grid;place-items:center;color:var(--ent-orange)}.entEngRow strong{font-size:11px}.entEngRow small{display:block;color:var(--ent-muted);font-size:8px;margin-top:3px}.entEngRow b{font-size:17px;direction:ltr}
 .entSectionToolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.entSearch{height:44px;border:1px solid var(--ent-line);background:var(--ent-card);border-radius:13px;display:flex;align-items:center;gap:8px;padding:0 12px;width:min(100%,400px)}.entSearch input{border:0;outline:0;background:transparent;color:var(--ent-text);width:100%;font-size:11px;text-align:right}.entSearch svg{color:var(--ent-muted);width:17px!important;height:17px!important}
 .entFeatureGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.entFeature{border:1px solid var(--ent-line);background:var(--ent-card);border-radius:18px;padding:18px;min-height:170px;box-shadow:var(--ent-shadow);display:flex;flex-direction:column}.entFeatureIcon{width:44px;height:44px;border-radius:13px;background:#fff0e8;color:var(--ent-orange);display:grid;place-items:center}.entFeature h3{font-size:14px;margin:15px 0 6px}.entFeature p{font-size:9px;line-height:1.7;color:var(--ent-muted);margin:0 0 15px}.entFeature button{margin-top:auto;align-self:flex-start}
 .entEmpty{min-height:180px;border:1px dashed var(--ent-line);border-radius:16px;background:var(--ent-soft);display:grid;place-items:center;text-align:center;color:var(--ent-muted);font-size:10px;padding:20px}.entActivity{display:grid;gap:8px}.entActivityRow{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px;border-bottom:1px solid var(--ent-line)}.entActivityRow:last-child{border-bottom:0}.entActivityIcon{width:38px;height:38px;border-radius:12px;background:var(--ent-soft);display:grid;place-items:center;color:var(--ent-muted)}.entActivityRow strong{font-size:10px}.entActivityRow small{display:block;color:var(--ent-muted);font-size:8px;margin-top:4px}.entActivityRow time{font-size:8px;color:var(--ent-muted)}
 .entSettingsGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.entSettingCard{border:1px solid var(--ent-line);background:var(--ent-card);border-radius:18px;padding:18px}.entSettingCard h3{font-size:14px;margin:0 0 5px}.entSettingCard p{font-size:9px;line-height:1.7;color:var(--ent-muted);margin:0 0 15px}.entThemeGroup{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.entThemeGroup button{height:38px;border:1px solid var(--ent-line);border-radius:10px;background:var(--ent-soft);color:var(--ent-text);font-size:9px;font-weight:850;cursor:pointer}.entThemeGroup button.active{border-color:#ff9a70;background:#fff1e9;color:var(--ent-orange)}html[data-theme='dark'] .entThemeGroup button.active{background:#2c1b14}
 .entBackdrop{display:none}
 @media(max-width:1020px){#${SHELL_ID}{grid-template-columns:minmax(0,1fr) 226px}.entKpis{grid-template-columns:1fr 1fr}.entFeatureGrid{grid-template-columns:1fr 1fr}.entContent{width:min(calc(100% - 32px),1200px)}}
 @media(max-width:760px){#${SHELL_ID}{display:block}.entSidebar{position:fixed;right:0;top:0;width:min(84vw,300px);height:100dvh;transform:translateX(105%);transition:.22s ease;box-shadow:-20px 0 50px rgba(0,0,0,.26)}#${SHELL_ID}.menuOpen .entSidebar{transform:translateX(0)}.entBackdrop{display:block;position:fixed;inset:0;background:rgba(0,0,0,.48);z-index:90;opacity:0;pointer-events:none;transition:.2s}#${SHELL_ID}.menuOpen .entBackdrop{opacity:1;pointer-events:auto}.entTopbar{height:72px;padding:0 14px}.entTopTitle h1{font-size:17px}.entTopTitle p{display:none}.entMobileMenu{display:grid}.entTopActions .hideMobile{display:none}.entContent{width:calc(100% - 20px);padding:16px 0 90px}.entHero{align-items:flex-start;flex-direction:column;margin-bottom:13px}.entHero h2{font-size:22px}.entHeroActions{width:100%}.entHeroActions button{flex:1}.entKpis{gap:8px}.entKpi{min-height:112px;padding:14px;border-radius:16px}.entKpi strong{font-size:25px}.entGrid2{grid-template-columns:1fr}.entFeatureGrid{grid-template-columns:1fr}.entSettingsGrid{grid-template-columns:1fr}.entSectionToolbar{align-items:stretch;flex-direction:column}.entSearch{width:100%;max-width:none}.entCard{border-radius:17px}.entCardHead{padding:13px 14px}.entCardBody{padding:13px 14px}}
 @media(max-width:430px){.entKpis{grid-template-columns:1fr 1fr}.entKpi{min-height:105px}.entKpiIcon{width:34px;height:34px}.entKpi strong{font-size:23px}.entKpi small{font-size:7.5px}.entTopActions{gap:5px}.entIconButton{width:38px;height:38px}.entTopTitle h1{font-size:16px}.entPrimary,.entSecondary{height:40px;padding:0 10px;font-size:10px}}
 `;document.head.appendChild(style);
}

function navItems(){
 const p=profile();return [
  ['dashboard','نظرة عامة',icons.dashboard,true],
  ['cars','السيارات والمخزون',icons.cars,can('carsView')],
  ['analytics','التحليلات والتقارير',icons.analytics,can('analyticsView')],
  ['team','الفريق والصلاحيات',icons.team,Boolean(p.isOwner)],
  ['users','المستخدمون',icons.users,can('usersView')],
  ['activity','سجل النشاط',icons.activity,Boolean(p.isOwner)],
  ['settings','الإعدادات',icons.settings,true],
 ].filter(x=>x[3]);
}
function viewTitle(){return ({dashboard:['مركز الإدارة','ملخص الأداء والعمليات'],cars:['السيارات والمخزون','إدارة جميع السيارات والحالات'],analytics:['التحليلات والتقارير','مؤشرات الزيارات وتفاعل العملاء'],team:['الفريق والصلاحيات','إدارة الموظفين وأدوار الوصول'],users:['المستخدمون','قاعدة مستخدمي MauriOne'],activity:['سجل النشاط','تتبع العمليات الإدارية'],settings:['إعدادات الإدارة','إعدادات مستقلة للوحة التحكم']})[state.view]||['لوحة التحكم','']}

function shellMarkup(){
 const [title,sub]=viewTitle();const p=profile();
 return `<div class="entBackdrop" data-action="close-menu"></div><aside class="entSidebar"><div class="entBrand"><b>Mauri</b><i>One</i></div><div class="entCompany"><strong>Administration Center</strong><small>MAURIONE CARS · MAURITANIA</small></div><nav class="entNav"><div class="entNavLabel">الإدارة</div>${navItems().map(([id,label,icon])=>`<button data-view="${id}" class="${state.view===id?'active':''}">${icon}<span>${label}</span></button>`).join('')}</nav><div class="entSidebarBottom"><div class="entProfile"><div class="entAvatar">${esc((p.displayName||'M')[0]||'M')}</div><div><strong>${esc(p.displayName||'مدير النظام')}</strong><small>${p.isOwner?'مالك النظام':esc(p.role||'عضو فريق')}</small></div></div></div></aside><main class="entMain"><header class="entTopbar"><div class="entTopTitle"><h1>${title}</h1><p>${sub}</p></div><div class="entTopActions"><button class="entIconButton entMobileMenu" data-action="toggle-menu">${icons.menu}</button><button class="entIconButton hideMobile" data-action="settings" title="الإعدادات">${icons.settings}</button><button class="entIconButton hideMobile" title="الإشعارات">${icons.bell}</button><button class="entSecondary hideMobile" data-action="open-site">${icons.external}<span>فتح الموقع</span></button>${can('carsCreate')?`<button class="entPrimary" data-action="add-car">${icons.plus}<span>إضافة سيارة</span></button>`:''}</div></header><section class="entContent" id="entContent"></section></main>`;
}

function kpi(icon,label,value,note,cls=''){return `<article class="entKpi"><div class="entKpiTop"><span class="entKpiLabel">${label}</span><span class="entKpiIcon ${cls}">${icon}</span></div><strong>${num(value)}</strong><small>${note}</small></article>`}
function recentCarsTable(cars=state.cars.slice(0,6),actions=false){if(!cars.length)return '<div class="entEmpty">لا توجد سيارات مسجلة حتى الآن.</div>';return `<div class="entTableWrap"><table class="entTable"><thead><tr><th>السيارة</th><th>السعر</th><th>الحالة</th><th>الموقع</th><th>آخر تحديث</th>${actions?'<th>إجراء</th>':''}</tr></thead><tbody>${cars.map((c,i)=>`<tr><td><div class="entCarCell">${c.images?.[0]?`<img class="entCarThumb" src="${esc(c.images[0])}" alt="">`:'<div class="entCarThumb"></div>'}<div><strong>${esc(carTitle(c))}</strong><small>${esc(c.trim||c.bodyType||'')}</small></div></div></td><td>${money(c.price)}</td><td><span class="entBadge ${c.status==='sold'?'sold':'available'}">${c.status==='sold'?'مباعة':'متوفرة'}</span></td><td>${esc(c.location||'—')}</td><td>${dateText(c.updatedAt||c.createdAt)}</td>${actions?`<td><div class="entRowActions">${can('carsEdit')?`<button class="entMini" data-action="edit-car" data-index="${state.cars.indexOf(c)}">تعديل</button>`:''}${can('carsMarkSold')?`<button class="entMini" data-action="toggle-car" data-index="${state.cars.indexOf(c)}">${c.status==='sold'?'إرجاع':'مباعة'}</button>`:''}${can('carsDelete')?`<button class="entMini danger" data-action="delete-car" data-index="${state.cars.indexOf(c)}">حذف</button>`:''}</div></td>`:''}</tr>`).join('')}</tbody></table></div>`}

function dashboardMarkup(){
 const totals=statTotals();const available=state.cars.filter(c=>c.status!=='sold').length,sold=state.cars.length-available,featured=state.cars.filter(c=>c.featured).length;const days=visitorDays();const max=Math.max(1,...days.map(d=>d.value));
 return `<div class="entHero"><div><h2>مرحبًا، ${esc(profile().displayName||'مدير النظام')}</h2><p>هذه نظرة تنفيذية مباشرة على أداء MauriOne Cars.</p></div><div class="entHeroActions">${can('carsCreate')?`<button class="entPrimary" data-action="add-car">${icons.plus} سيارة جديدة</button>`:''}<button class="entSecondary" data-view="analytics">${icons.analytics} التقارير</button></div></div><div class="entKpis">${kpi(icons.cars,'إجمالي السيارات',state.cars.length,`${available} متوفرة حاليًا`,'orange')}${kpi(icons.eye,'إجمالي المشاهدات',totals.views,'مشاهدات صفحات السيارات')}${kpi(icons.wa,'طلبات واتساب',totals.whatsappClicks,'تفاعل مباشر من العملاء','green')}${kpi(icons.users,'إجمالي الزوار',visitorTotal(),`${featured} سيارات مميزة`)}</div><div class="entGrid2"><section class="entCard"><div class="entCardHead"><div><h3>حركة الزوار</h3><span>آخر 7 أيام</span></div><button class="entLinkButton" data-view="analytics">عرض التقرير</button></div><div class="entCardBody">${days.length?`<div class="entBars">${days.map(d=>`<div class="entBarCol"><div class="entBarTrack"><div class="entBar" style="height:${Math.max(4,Math.round(d.value/max*100))}%"></div></div><strong>${num(d.value)}</strong><span>${d.day.slice(5)}</span></div>`).join('')}</div>`:'<div class="entEmpty">ستظهر بيانات الزيارات هنا بعد جمعها.</div>'}</div></section><section class="entCard"><div class="entCardHead"><div><h3>تفاعل العملاء</h3><span>إجمالي التفاعل</span></div></div><div class="entCardBody"><div class="entEngagement"><div class="entEngRow"><div class="entEngIcon">${icons.eye}</div><div><strong>مشاهدات السيارات</strong><small>فتح صفحات التفاصيل</small></div><b>${num(totals.views)}</b></div><div class="entEngRow"><div class="entEngIcon">${icons.wa}</div><div><strong>واتساب</strong><small>طلبات التواصل</small></div><b>${num(totals.whatsappClicks)}</b></div><div class="entEngRow"><div class="entEngIcon">${icons.phone}</div><div><strong>الاتصالات</strong><small>ضغطات رقم الهاتف</small></div><b>${num(totals.phoneClicks)}</b></div><div class="entEngRow"><div class="entEngIcon">${icons.heart}</div><div><strong>المفضلة</strong><small>إضافات المستخدمين</small></div><b>${num(totals.favoriteAdds)}</b></div></div></div></section></div><section class="entCard" style="margin-top:14px"><div class="entCardHead"><div><h3>أحدث السيارات</h3><span>${state.cars.length} سيارة في النظام · ${sold} مباعة</span></div><button class="entLinkButton" data-view="cars">إدارة المخزون</button></div>${recentCarsTable()}</section>`;
}
function carsMarkup(){const q=state.search.trim().toLowerCase();const cars=q?state.cars.filter(c=>`${carTitle(c)} ${c.location||''} ${c.trim||''}`.toLowerCase().includes(q)):state.cars;return `<div class="entHero"><div><h2>السيارات والمخزون</h2><p>إدارة بيانات السيارات، حالتها، أسعارها وصورها من مكان واحد.</p></div>${can('carsCreate')?`<button class="entPrimary" data-action="add-car">${icons.plus} إضافة سيارة</button>`:''}</div><div class="entSectionToolbar"><label class="entSearch">${icons.search}<input id="entCarSearch" value="${esc(state.search)}" placeholder="ابحث بالماركة، الموديل أو الموقع..."></label><div><span class="entBadge">${cars.length} نتيجة</span></div></div><section class="entCard">${recentCarsTable(cars,true)}</section>`}
function analyticsMarkup(){const t=statTotals(),days=visitorDays(),max=Math.max(1,...days.map(d=>d.value));return `<div class="entHero"><div><h2>التحليلات والتقارير</h2><p>قراءة موحدة لسلوك الزوار ومدى اهتمامهم بالسيارات.</p></div></div><div class="entKpis">${kpi(icons.eye,'المشاهدات',t.views,'كل صفحات السيارات','orange')}${kpi(icons.wa,'واتساب',t.whatsappClicks,'نقرات التواصل','green')}${kpi(icons.phone,'الاتصالات',t.phoneClicks,'نقرات الاتصال')}${kpi(icons.heart,'المفضلة',t.favoriteAdds,'إضافات للمفضلة')}</div><div class="entGrid2"><section class="entCard"><div class="entCardHead"><div><h3>الزيارات اليومية</h3><span>آخر 7 أيام</span></div></div><div class="entCardBody">${days.length?`<div class="entBars">${days.map(d=>`<div class="entBarCol"><div class="entBarTrack"><div class="entBar" style="height:${Math.max(4,Math.round(d.value/max*100))}%"></div></div><strong>${num(d.value)}</strong><span>${d.day.slice(5)}</span></div>`).join('')}</div>`:'<div class="entEmpty">لا توجد بيانات كافية بعد.</div>'}</div></section><section class="entCard"><div class="entCardHead"><div><h3>مؤشرات التحويل</h3><span>من المشاهدة إلى التواصل</span></div></div><div class="entCardBody"><div class="entEngagement"><div class="entEngRow"><div class="entEngIcon">${icons.wa}</div><div><strong>معدل واتساب</strong><small>من إجمالي المشاهدات</small></div><b>${t.views?((t.whatsappClicks/t.views)*100).toFixed(1):'0.0'}%</b></div><div class="entEngRow"><div class="entEngIcon">${icons.phone}</div><div><strong>معدل الاتصال</strong><small>من إجمالي المشاهدات</small></div><b>${t.views?((t.phoneClicks/t.views)*100).toFixed(1):'0.0'}%</b></div><div class="entEngRow"><div class="entEngIcon">${icons.heart}</div><div><strong>معدل الحفظ</strong><small>من إجمالي المشاهدات</small></div><b>${t.views?((t.favoriteAdds/t.views)*100).toFixed(1):'0.0'}%</b></div></div></div></section></div>`}
function teamMarkup(){return `<div class="entHero"><div><h2>الفريق والصلاحيات</h2><p>إدارة من يستطيع الوصول وما الذي يستطيع تنفيذه داخل النظام.</p></div></div><div class="entFeatureGrid"><article class="entFeature"><div class="entFeatureIcon">${icons.team}</div><h3>أعضاء الفريق</h3><p>إنشاء الموظفين، إيقاف الحسابات، وتحديد دور كل عضو.</p><button class="entPrimary" data-action="team-manager">فتح إدارة الفريق</button></article><article class="entFeature"><div class="entFeatureIcon">${icons.settings}</div><h3>الصلاحيات الدقيقة</h3><p>منح صلاحيات منفصلة للمشاهدة والإضافة والتعديل والحذف والتقارير.</p><button class="entSecondary" data-action="team-manager">إدارة الصلاحيات</button></article><article class="entFeature"><div class="entFeatureIcon">${icons.activity}</div><h3>الرقابة والنشاط</h3><p>متابعة العمليات الإدارية ومعرفة من قام بكل إجراء.</p><button class="entSecondary" data-view="activity">سجل النشاط</button></article></div>`}
function usersMarkup(){return `<div class="entHero"><div><h2>المستخدمون</h2><p>عرض قاعدة الحسابات المسجلة في MauriOne ومعلوماتها الأساسية.</p></div></div><div class="entFeatureGrid"><article class="entFeature"><div class="entFeatureIcon">${icons.users}</div><h3>دليل المستخدمين</h3><p>استعراض المستخدمين المسجلين والبحث بينهم وفتح بيانات التواصل المتاحة.</p><button class="entPrimary" data-action="users-manager">فتح دليل المستخدمين</button></article></div>`}
function activityMarkup(){return `<div class="entHero"><div><h2>سجل النشاط</h2><p>سجل تدقيق للعمليات التي تتم داخل لوحة الإدارة.</p></div></div><section class="entCard"><div class="entCardHead"><div><h3>آخر العمليات</h3><span>${state.activity.length} عملية مسجلة</span></div></div><div class="entCardBody">${state.activity.length?`<div class="entActivity">${state.activity.slice(0,40).map(a=>`<div class="entActivityRow"><div class="entActivityIcon">${icons.activity}</div><div><strong>${esc(a.action||a.type||'عملية إدارية')}</strong><small>${esc(a.actorName||a.displayName||a.uid||'النظام')} ${a.target?`· ${esc(a.target)}`:''}</small></div><time>${dateText(a.createdAt||a.timestamp)}</time></div>`).join('')}</div>`:'<div class="entEmpty">عند بدء تسجيل العمليات ستظهر هنا تلقائيًا.</div>'}</div></section>`}
function settingsMarkup(){let theme='system';try{theme=localStorage.getItem('maurione_admin_theme')||'system'}catch{}return `<div class="entHero"><div><h2>إعدادات لوحة الإدارة</h2><p>هذه الإعدادات مستقلة عن واجهة موقع الزوار.</p></div></div><div class="entSettingsGrid"><article class="entSettingCard"><h3>المظهر</h3><p>حدد مظهر لوحة الإدارة على هذا الجهاز.</p><div class="entThemeGroup"><button data-theme-choice="light" class="${theme==='light'?'active':''}">فاتح</button><button data-theme-choice="dark" class="${theme==='dark'?'active':''}">داكن</button><button data-theme-choice="system" class="${theme==='system'?'active':''}">تلقائي</button></div></article><article class="entSettingCard"><h3>إعدادات متقدمة</h3><p>إعدادات إظهار الإحصائيات والأقسام الإدارية الإضافية.</p><button class="entSecondary" data-action="legacy-settings">فتح الإعدادات المتقدمة</button></article></div>`}

function contentMarkup(){if(state.view==='cars')return carsMarkup();if(state.view==='analytics')return analyticsMarkup();if(state.view==='team')return teamMarkup();if(state.view==='users')return usersMarkup();if(state.view==='activity')return activityMarkup();if(state.view==='settings')return settingsMarkup();return dashboardMarkup()}
function render(){
 renderQueued=false;const shell=document.getElementById(SHELL_ID);if(!shell)return;const [title,sub]=viewTitle();shell.classList.toggle('menuOpen',state.mobileMenu);shell.querySelector('.entTopTitle h1').textContent=title;shell.querySelector('.entTopTitle p').textContent=sub;shell.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view&&b.closest('.entNav')));const c=shell.querySelector('#entContent');if(c)c.innerHTML=contentMarkup();
}
function scheduleRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(render)}
function findOriginalAction(type,index){const admin=document.querySelector('.mxAdmin');if(!admin)return null;if(type==='add')return [...admin.querySelectorAll('.mxAdminActions button')].find(b=>String(b.textContent).includes('إضافة سيارة'));const article=admin.querySelectorAll('.mxAdminList article')[Number(index)];if(!article)return null;const buttons=[...article.querySelectorAll('.mxRowButtons button')];return type==='toggle'?buttons[0]:type==='edit'?buttons[1]:type==='delete'?buttons[2]:null}
function clickOriginal(type,index){const b=findOriginalAction(type,index);if(b){b.click();return true}return false}
async function openTeam(){try{await import('./admin-team-manager.js')}catch(e){console.warn(e)}setTimeout(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.classList.contains('mxAdminTeamButton')||String(x.textContent).includes('الفريق والصلاحيات'));if(b&&b.closest(`#${SHELL_ID}`)==null)b.click()},100)}
async function openUsers(){try{await import('./admin-users.js')}catch(e){console.warn(e)}setTimeout(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.classList.contains('mxAdminUsersButton')||String(x.textContent).trim()==='المستخدمون');if(b&&b.closest(`#${SHELL_ID}`)==null)b.click()},100)}
function legacySettings(){const b=document.querySelector('.mxAdminSettingsButton[data-admin-header-settings="1"]')||document.querySelector('.mxAdminSettingsButton');b?.click()}
function applyThemeChoice(choice){try{localStorage.setItem('maurione_admin_theme',choice)}catch{}const resolved=choice==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):choice;document.documentElement.dataset.theme=resolved;document.documentElement.style.colorScheme=resolved;scheduleRender()}
function bind(shell){shell.addEventListener('click',e=>{const target=e.target.closest('button,[data-action],[data-view]');if(!target)return;const view=target.dataset.view;if(view){state.view=view;state.mobileMenu=false;scheduleRender();return}const a=target.dataset.action;if(a==='toggle-menu'){state.mobileMenu=!state.mobileMenu;scheduleRender()}else if(a==='close-menu'){state.mobileMenu=false;scheduleRender()}else if(a==='open-site')location.assign('/?from=admin-preview&t='+Date.now());else if(a==='add-car')clickOriginal('add');else if(a==='edit-car')clickOriginal('edit',target.dataset.index);else if(a==='toggle-car')clickOriginal('toggle',target.dataset.index);else if(a==='delete-car')clickOriginal('delete',target.dataset.index);else if(a==='team-manager')openTeam();else if(a==='users-manager')openUsers();else if(a==='settings'||a==='legacy-settings')legacySettings()});shell.addEventListener('input',e=>{if(e.target.id==='entCarSearch'){state.search=e.target.value;const pos=e.target.selectionStart;scheduleRender();requestAnimationFrame(()=>{const input=document.getElementById('entCarSearch');if(input){input.focus();try{input.setSelectionRange(pos,pos)}catch{}}})}});shell.addEventListener('click',e=>{const b=e.target.closest('[data-theme-choice]');if(b)applyThemeChoice(b.dataset.themeChoice)})}
function subscribe(){if(!db)return;state.stops.forEach(fn=>{try{fn()}catch{}});state.stops=[];state.stops.push(onSnapshot(query(collection(db,'cars'),orderBy('createdAt','desc')),s=>{state.cars=s.docs.map(d=>({id:d.id,...d.data()}));scheduleRender()},()=>{}));if(can('analyticsView'))state.stops.push(onSnapshot(collection(db,'carStats'),s=>{state.stats=s.docs.map(d=>({id:d.id,...d.data()}));scheduleRender()},()=>{}));if(profile().isOwner){state.stops.push(onSnapshot(collection(db,'admins'),s=>{state.admins=s.docs.map(d=>({id:d.id,...d.data()}));scheduleRender()},()=>{}));try{state.stops.push(onSnapshot(query(collection(db,'adminActivity'),orderBy('createdAt','desc')),s=>{state.activity=s.docs.map(d=>({id:d.id,...d.data()}));scheduleRender()},()=>{}))}catch{}}
}
function mount(){const admin=document.querySelector('.mxAdmin');if(!admin||document.getElementById(SHELL_ID))return false;ensureStyle();document.body.classList.add('mxEnterpriseActive');const shell=document.createElement('div');shell.id=SHELL_ID;shell.innerHTML=shellMarkup();admin.prepend(shell);bind(shell);subscribe();render();return true}
function start(){if(started)return;started=true;if(mount())return;const observer=new MutationObserver(()=>{if(mount())observer.disconnect()});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),20000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
window.addEventListener('beforeunload',()=>state.stops.forEach(fn=>{try{fn()}catch{}}));
